#services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=1234567890'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
