server:
    port: 8082

spring:
    application:
        name: task-manager
    data:
        mongodb:
            uri: mongodb://root:1234567890@localhost:27017/tasks-manager?authSource=admin
            port: 27017
            database: tasks-manager
            username: root
            password: 1234567890
            authentication-database: admin
            repositories:
                enable: true

aws:
    s3:
        bucket:
            name: task-manager-bucket
        access-key-id: accesskey
        secret-access-key: secretKey
        localstack-url: http://localhost:4566

logging:
    level:
        org:
            springframework:
                data:
                    mongodb: DEBUG


